/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.pdc.taqmac.dsl.validation;

import fr.ut2j.m1ice.pdc.taqmac.dsl.validation.AbstractTaqmacValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TaqmacValidator extends AbstractTaqmacValidator {
}
