matrix:
  # include:
  #   - language: node_js
  #   node_js: lts/*
  #   before_script:
  #     - cd front
  #     - npm ci
  #   script:
  #     npm test
  include:
    - language: java
    jdk: openjdk11

notifications:
  email:
    - adrien.stora@gmail.com
    - corentin.grandchamps@gmail.com
    - ancelin.glories@gmail.com