/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.pdc.taqmac.dsl.ui;

import fr.ut2j.m1ice.pdc.taqmac.dsl.ui.AbstractTaqmacUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TaqmacUiModule extends AbstractTaqmacUiModule {
  public TaqmacUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
