/*
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.pdc.taqmac.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TaqmacRuntimeModule extends AbstractTaqmacRuntimeModule {
}
