/*
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.pdc.taqmac.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TaqmacStandaloneSetup extends TaqmacStandaloneSetupGenerated {

	def static void doSetup() {
		new TaqmacStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
