/*
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.pdc.taqmac.dsl.formatting2

import com.google.inject.Inject
import fr.ut2j.m1ice.pdc.taqmac.dsl.services.TaqmacGrammarAccess
import org.eclipse.xtext.formatting2.AbstractFormatter2

class TaqmacFormatter extends AbstractFormatter2 {
	
	@Inject extension TaqmacGrammarAccess
	
	// TODO: implement for 
}
