/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.pdc.taqmac.dsl.scoping;

import fr.ut2j.m1ice.pdc.taqmac.dsl.scoping.AbstractTaqmacScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class TaqmacScopeProvider extends AbstractTaqmacScopeProvider {
}
