/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.pdc.taqmac.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.ut2j.m1ice.pdc.taqmac.dsl.TaqmacRuntimeModule;
import fr.ut2j.m1ice.pdc.taqmac.dsl.TaqmacStandaloneSetup;
import fr.ut2j.m1ice.pdc.taqmac.dsl.ide.TaqmacIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TaqmacIdeSetup extends TaqmacStandaloneSetup {
  @Override
  public Injector createInjector() {
    TaqmacRuntimeModule _taqmacRuntimeModule = new TaqmacRuntimeModule();
    TaqmacIdeModule _taqmacIdeModule = new TaqmacIdeModule();
    return Guice.createInjector(Modules2.mixin(_taqmacRuntimeModule, _taqmacIdeModule));
  }
}
