/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.pdc.taqmac.dsl.ide;

import fr.ut2j.m1ice.pdc.taqmac.dsl.ide.AbstractTaqmacIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TaqmacIdeModule extends AbstractTaqmacIdeModule {
}
