/*
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.pdc.taqmac.dsl.ui.tests;

import com.google.inject.Injector;
import fr.ut2j.m1ice.pdc.taqmac.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TaqmacUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("fr.ut2j.m1ice.pdc.taqmac.dsl.Taqmac");
	}

}
