/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.pdc.taqmac.dsl;

import fr.ut2j.m1ice.pdc.taqmac.dsl.TaqmacStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TaqmacStandaloneSetup extends TaqmacStandaloneSetupGenerated {
  public static void doSetup() {
    new TaqmacStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
