/*
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.pdc.taqmac.dsl.parser.antlr;

import com.google.inject.Inject;
import fr.ut2j.m1ice.pdc.taqmac.dsl.parser.antlr.internal.InternalTaqmacParser;
import fr.ut2j.m1ice.pdc.taqmac.dsl.services.TaqmacGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TaqmacParser extends AbstractAntlrParser {

	@Inject
	private TaqmacGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTaqmacParser createParser(XtextTokenStream stream) {
		return new InternalTaqmacParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Itineraire";
	}

	public TaqmacGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TaqmacGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
